# Generated by Django 3.1 on 2022-02-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
        migrations.RenameField(
            model_name='reviewrating',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reviewrating',
            old_name='update_date',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(max_length=255, upload_to='store/products'),
        ),
    ]
